"""initial poc schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-12 18:26:45.893551
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

import dbpoc.schema

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_identity',
    sa.Column('id', dbpoc.schema.NativeUuid(), nullable=False),
    sa.Column('tcg', sa.String(length=32), nullable=False),
    sa.Column('set_code', sa.String(length=32), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('rarity', sa.String(length=32), nullable=False),
    sa.Column('edition', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tcg', 'set_code', 'card_number', 'rarity', 'edition', 'language', name='uq_card_identity_attributes'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_card_identity_normalized_name', 'card_identity', ['normalized_name'], unique=False)
    op.create_table('shop',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('source',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stopped_reason', sa.String(length=200), nullable=True),
    sa.Column('last_success_run_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint("state IN ('active','paused','stopped')", name='ck_source_state'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('card_external_reference',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_identity_id', dbpoc.schema.NativeUuid(), nullable=False),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('evidence', sa.String(length=120), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['card_identity_id'], ['card_identity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'external_id', name='uq_card_external_reference'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('ingest_run',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('stored_count', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=40), nullable=True),
    sa.CheckConstraint("status IN ('succeeded','partial','failed','empty','running')", name='ck_ingest_run_status'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_ingest_run_source_started', 'ingest_run', ['source_id', 'started_at'], unique=False)
    op.create_table('raw_artifact',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_item_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('storage_ref', sa.String(length=300), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name='ck_raw_artifact_byte_size'),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_raw_artifact_source_hash'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_raw_artifact_fetched_at', 'raw_artifact', ['fetched_at'], unique=False)
    op.create_table('processing_run',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('raw_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('processor_name', sa.String(length=64), nullable=False),
    sa.Column('processor_version', sa.String(length=32), nullable=False),
    sa.Column('config_ref', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('extracted_count', sa.Integer(), nullable=False),
    sa.Column('promoted_count', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_artifact_id', 'processor_name', 'processor_version', 'config_ref', 'attempt_no', name='uq_processing_run_reparse'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('extracted_record',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('processing_run_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('locator', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('value_origin', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('warnings', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_run.id'], ),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_extracted_record_artifact', 'extracted_record', ['raw_artifact_id'], unique=False)
    op.create_index('ix_extracted_record_processing_run', 'extracted_record', ['processing_run_id'], unique=False)
    op.create_table('observation_candidate',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('extracted_record_id', sa.BigInteger(), nullable=False),
    sa.Column('shop_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('tcg', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('price_type', sa.String(length=16), nullable=False),
    sa.Column('raw_card_name', sa.String(length=200), nullable=False),
    sa.Column('raw_card_number', sa.String(length=32), nullable=True),
    sa.Column('raw_set', sa.String(length=32), nullable=True),
    sa.Column('raw_rarity', sa.String(length=32), nullable=True),
    sa.Column('raw_edition', sa.String(length=32), nullable=True),
    sa.Column('raw_language', sa.String(length=8), nullable=True),
    sa.Column('raw_condition', sa.String(length=16), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('promotion_rule_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("price_type IN ('buy','sell')", name='ck_candidate_price_type'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_candidate_amount_non_negative'),
    sa.ForeignKeyConstraint(['extracted_record_id'], ['extracted_record.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extracted_record_id', 'promotion_rule_version', name='uq_candidate_record_rule'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('identity_resolution_attempt',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('observation_candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('matcher_name', sa.String(length=64), nullable=False),
    sa.Column('matcher_version', sa.String(length=32), nullable=False),
    sa.Column('card_identity_id', dbpoc.schema.NativeUuid(), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("result IN ('confirmed','rejected','ambiguous')", name='ck_attempt_result'),
    sa.CheckConstraint('match_score >= 0 AND match_score <= 1', name='ck_attempt_score_range'),
    sa.ForeignKeyConstraint(['card_identity_id'], ['card_identity.id'], ),
    sa.ForeignKeyConstraint(['observation_candidate_id'], ['observation_candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_attempt_candidate', 'identity_resolution_attempt', ['observation_candidate_id'], unique=False)
    op.create_table('price_observation',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('observation_candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('card_identity_id', dbpoc.schema.NativeUuid(), nullable=False),
    sa.Column('shop_id', sa.SmallInteger(), nullable=False),
    sa.Column('source_id', sa.SmallInteger(), nullable=False),
    sa.Column('raw_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('tcg', sa.String(length=32), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('price_type', sa.String(length=16), nullable=False),
    sa.Column('card_condition', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("price_type IN ('buy','sell')", name='ck_observation_price_type'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_observation_amount_non_negative'),
    sa.ForeignKeyConstraint(['card_identity_id'], ['card_identity.id'], ),
    sa.ForeignKeyConstraint(['observation_candidate_id'], ['observation_candidate.id'], ),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifact.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_price_observation_idempotency'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_observation_candidate', 'price_observation', ['observation_candidate_id'], unique=False)
    op.create_index('ix_observation_card_observed', 'price_observation', ['card_identity_id', 'observed_at'], unique=False)
    op.create_index('ix_observation_card_shop_observed', 'price_observation', ['card_identity_id', 'shop_id', 'observed_at'], unique=False)
    op.create_index('ix_observation_collected_at', 'price_observation', ['collected_at'], unique=False)
    op.create_table('price_observation_correction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('price_observation_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('rule_version', sa.String(length=32), nullable=False),
    sa.Column('replacement_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.CheckConstraint("action IN ('invalidate','supersede','restore')", name='ck_correction_action'),
    sa.ForeignKeyConstraint(['price_observation_id'], ['price_observation.id'], ),
    sa.ForeignKeyConstraint(['replacement_id'], ['price_observation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_correction_observation', 'price_observation_correction', ['price_observation_id', 'id'], unique=False)
    op.create_table('review_item',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('ingest_run_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('extracted_record_id', sa.BigInteger(), nullable=True),
    sa.Column('identity_resolution_attempt_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True).with_variant(mysql.DATETIME(fsp=6), 'mariadb').with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("state IN ('pending','decided','dismissed')", name='ck_review_state'),
    sa.ForeignKeyConstraint(['extracted_record_id'], ['extracted_record.id'], ),
    sa.ForeignKeyConstraint(['identity_resolution_attempt_id'], ['identity_resolution_attempt.id'], ),
    sa.ForeignKeyConstraint(['ingest_run_id'], ['ingest_run.id'], ),
    sa.ForeignKeyConstraint(['raw_artifact_id'], ['raw_artifact.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_review_state_priority', 'review_item', ['state', 'priority', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_state_priority', table_name='review_item')
    op.drop_table('review_item')
    op.drop_index('ix_correction_observation', table_name='price_observation_correction')
    op.drop_table('price_observation_correction')
    op.drop_index('ix_observation_collected_at', table_name='price_observation')
    op.drop_index('ix_observation_card_shop_observed', table_name='price_observation')
    op.drop_index('ix_observation_card_observed', table_name='price_observation')
    op.drop_index('ix_observation_candidate', table_name='price_observation')
    op.drop_table('price_observation')
    op.drop_index('ix_attempt_candidate', table_name='identity_resolution_attempt')
    op.drop_table('identity_resolution_attempt')
    op.drop_table('observation_candidate')
    op.drop_index('ix_extracted_record_processing_run', table_name='extracted_record')
    op.drop_index('ix_extracted_record_artifact', table_name='extracted_record')
    op.drop_table('extracted_record')
    op.drop_table('processing_run')
    op.drop_index('ix_raw_artifact_fetched_at', table_name='raw_artifact')
    op.drop_table('raw_artifact')
    op.drop_index('ix_ingest_run_source_started', table_name='ingest_run')
    op.drop_table('ingest_run')
    op.drop_table('card_external_reference')
    op.drop_table('source')
    op.drop_table('shop')
    op.drop_index('ix_card_identity_normalized_name', table_name='card_identity')
    op.drop_table('card_identity')
    # ### end Alembic commands ###
